Layr-Labs/eigenda-proxy

- commitment.go
**Changes**
* Converted `DaCommitment` to `GenericCommitment` to align with OP implementation
* Reduced server side encoding to only prepend `DA_TYPE, DA_VERSION` onto the commitment when writing to response body in put method since OP stack will handle the commitment type encoding
> Update commitment encoding

- .env.example
- .github/workflows/actions.yml
- Dockerfile
- Makefile
- README.md
- cmd/daserver/entrypoint.go
- cmd/daserver/flags.go
- cmd/daserver/main.go
- eigenda/config.go
- metrics/metrics.go
- server.go
- store/memory.go
- store/memory_test.go
- test/e2e_test.go
**Changes:**
- Add an ephemeral memory store DA backend which is usable via new feature flags
- Added mem store tests for key set/get and expiration flows
- Removed plasma reference in favor of proxy
**Fixes:** https://github.com/Layr-Labs/op-plasma-eigenda/issues/14
> feat: mem store

- .github/workflows/actions.yml
- Makefile
- README.md
- cmd/server/entrypoint.go
- cmd/server/main.go
- eigenda/commitment.go
- go.mod
- go.sum
- server/flags.go
- server/load_store.go
- server/server.go
- store/eigenda.go
- store/memory.go
- test/e2e_test.go
* moves LoadServer() and server.go into a new server package so that LoadServer() can be used in e2e_test.go (avoiding duplication of DI efforts)
* Removes GenericCommitmentByte from the returned commitment, since it is prepended by the OP client on the clients side..?
* Enable WithLogging() middleware
* Expand WithLogging() to support error logging, update handler signatures and implementations to tie into this
* Update path patterns to match the usage by the OP plasma client
> Update EigenDA proxy to match OP v1.7.6 client expectation

- README.md
- The previous version of the docs used a parameter (`eigenda-use-tls`) that wasn't longer available.
- Specifying a valid `eigenda-max-blob-length` is necessary. Otherwise an error is thrown:
```
INFO [06-18|16:04:11.833] Initializing EigenDA proxy server...     role=eigenda_proxy
INFO [06-18|16:04:11.834] Using eigenda backend                    role=eigenda_proxy
INFO [06-18|16:04:11.836] failed to read G1 points cannot read file unexpected EOF role=eigenda_proxy
CRIT [06-18|16:04:11.836] Application failed                       role=eigenda_proxy message="failed to create store: cannot read file unexpected EOF"
```
> Update docs on how to run the proxy locally

- client/client.go
- common/common.go
- e2e/server_test.go
- store/eigenda.go
his PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.
Hope it helps.
> Docs rectify typographical inaccuracies

- .github/workflows/actions.yml
- e2e/setup.go
- eigenda/config.go
- server/load_store.go
- store/eigenda.go
- store/memory.go
- store/memory_test.go
- verify/cert.go
- verify/hasher.go
- verify/hasher_test.go
- verify/verifier.go
- verify/verify_test.go
> feat: Batch hash verification

- server/server.go
> fix: Resolve commitment decoding bug

- README.md
Just fixing a simple typo: merkalized -> merkleized
> docs(README.md): fix typo

- scripts/op-devnet-allocs.sh
The ending "fi" for the if-statement was accidentally omitted.
> Fix syntax in op-devnet-allocs.sh

- server/server.go
changed the way get request metrics are recorded to group by commitmentHeader only.
Otherwise we get a gazillion requests and metrics explode (which would cost a loot of money on datadog)
> fix: rpc server metric label shortened to commitment header

- README.md
- server/config.go
- server/flags.go
* Updated readme documentation 
* Fix env ingestion for S3 fallback mode
* Minor refactors on CLI handling logic
> chore: Update commitment schemas in README

- metrics/metrics.go
- server/server.go
Main issue I wanted to resolve is changing the histogram buckets to be useful (see screenshot below).
We were using the optimism metrics which define buckets for their rpc use case, which don't make sense for our case.
So I just pulled in their code, and added a status code label to the requests_total metric.
> refactor(metrics): remove dependency on optimism metrics

- README.md
- server/config.go
Some users might take longer than 10sec to disperse blobs, when it timed out, the workload on disperser is completed prematurely, see(https://github.com/Layr-Labs/eigenda/blob/master/api/clients/eigenda_client.go#L45) and (https://github.com/Layr-Labs/eigenda/blob/master/disperser/apiserver/server.go#L283) whenever context is timedout
Although processing speed on disperser is less than 500ms, the transmission latency might high
> change disperseBlob response timeout to 60sec

- .env.example.holesky
- .env.example.mainnet
- README.md
- e2e/server_test.go
- server/config.go
- store/router.go
> chore: Update large blob test to use 16mb

- Makefile
- README.md
- cmd/server/entrypoint.go
- server/config.go
- server/flags.go
- server/load_store.go
- store/memory.go
- store/memory_test.go
Closes #86 
We want to test our op-batcher parallel blob submission with memstore backend. To test it, we need blob to actually take some time to disperse, so added option to add artificial latency to put/get requests.
> Feat memstore artificial latency

- Dockerfile
I personally prefer my dockerfiles that are meant to run a single binary to have that binary as the entrypoint. This way I just have to pass the flags directly and don't need to know how the binary was named inside the image.
Compare with this change
```
docker run eigenda-proxy:latest --memstore.enabled
```
to what we currently have
```
docker run eigenda-proxy:latest ./eigenda-proxy --memstore.enabled
```
This is wordy for no reason, but also I need to inspect Dockerfile manually to check where the binary is located.
This is a breaking change however, given that RaaS's or whoever has this setup in a docker-compose file somewhere will need to change their CMD to work with this (just remove the name of the binary)
> BREAKING suggestion: change dockerfile to use entrypoint instead of cmd

- Dockerfile
- Dockerfile.dockerignore
- Makefile
Cleanup dockerignore file to only copy into build the files that we need. More chance of hitting cache this way
Also renamed app_name in Makefile to use the full ghcr image name that we use. This way I can build locally with latest tag and use that in my op devnet compose file. Otherwise it was building an image with docker.io prefix (going to dockerhub).
> Chore give docker image fullname

- Makefile
This'll make it easier to test that the da-proxy is working manually. eg:
```
make run-memstore-server
make disperse-test-blob
```
> Update Makefile: add disperse-test-blob

- .env.example.holesky
- .env.example.mainnet
- README.md
- server/config.go
Needed for consistency with all other flags. For some reason MEMSTORE flags are the only ones without the EIGENDA_PROXY flag.
This is a breaking change for anyone who was running the proxy using the env var flags. They will need to add the prefix so we should communicate this change.
> chore(breaking): add EIGENDA_PROXY prefix to memstore flags

- cmd/server/entrypoint.go
Compare before:
```
CRIT [09-16|12:30:18.362] Application failed                       role=eigenda_proxy message="failed to start the DA server"
```
to after:
```
CRIT [09-16|12:32:56.571] Application failed                       role=eigenda_proxy message="failed to start the DA server: failed to listen: listen tcp 0.0.0.0:3100: bind: address already in use"
```
> fix: wrap crit entrypoint error for easier debugging

- server/config.go
- verify/cert.go
- verify/verifier.go
Fixes #123 
Still think that this confirmation depth feature should be in the eigenda-client itself and not here (see issue #130), but this at least fixes the bug.
> fix: negative confDepth bug in verifier

- Dockerfile
- Makefile
- cmd/server/entrypoint.go
- cmd/server/main.go
- server/server.go
- server/server_test.go
- verify/cert.go
- verify/verifier.go
See commit names for summary of changes.
> chore: bunch of small refactors for improved devex

- e2e/optimism_test.go
- e2e/server_test.go
- e2e/setup.go
- server/load_store.go
Fixes #128 
2 main things in this PR:
1. add a test to reproduce the panic
2. fix the test (https://github.com/Layr-Labs/eigenda-proxy/commit/d8c605b980b43a63559c278836afbe58de66910a)
I'm fine with using either this fix or the one in #125  
But if we want the one in #125 then we should still include the test from this PR.
> Fix s3 panic from keccak commitment put requests

- metrics/metrics.go
- server/server.go
- server/server_test.go
Recent metric changes were causing panics that weren't caught in tests because the tests never use the metrics and logs middlewares. Added testing for those, and fixed the panic.
Fixes #
> Fix metric middleware panic

- server/server.go
Bowen explained that if `HandlePut` is writing a request of commitment mode `op kaccek256`, the OP daclient will set the base part of the query as the hash digest, and not follow the commitment schema described in the eigenda-proxy README. We can't simply decode the request for `HandlePut`.
Since there's only one `CertEncodingCommitment` supported by EigenDA right now, the simple fix is to use default 0x0. The override happens after `ReadCommitmentMeta` in `HandlePut` and not inside `ReadCommitmentMeta` because `HandleGet` method is okay.
> fix: HandlePut uses hardcoded default version

- server/errors.go
- server/server.go
- server/server_test.go
Added a `HandlerError` type to contain error and commitment meta (mode and version) for metrics
> fix: custom error wrapped around error and commitment meta

- e2e/server_test.go
- server/server.go
- store/eigenda.go
- store/memory.go
- store/store.go
- utils/utils.go
Fixes https://github.com/Layr-Labs/eigenda-proxy/issues/127
> fix: Return 400 when blobs exceed max limit

- Makefile
- README.md
- server/config.go
- server/config_test.go
- server/load_store.go
- store/memory_test.go
- verify/verifier.go
- verify/verify_test.go
Since we merged the PR that fixed the `confDepth=-1` bug, now confDepth is always a non-negative number, so the conf checker is broken. Running `make run-memstore-server` results in this CRIT:
```
CRIT [09-19|21:18:50.564] Application failed                       role=eigenda_proxy message="eth confirmation depth is set for certificate verification, but Eth RPC or SvcManagerAddr is not set"
```
I changed the checks a bit arbitrarily... not super sure if it's correct, @epociask please take a good look. When using the memstore we don't need ethRPC or svsManagerAddr do we?
Tests are failing, waiting for correct semantic before changing them. Also removed the -v from `make test` because that prints too much garbage and is impossible to find the actual error when a test fails.
> Fix config checker logic

- server/server.go
Current behavior after put, it shows an empty string
This fix prints the response commitment
> show response commitment

- .github/workflows/holesky-test.yml
Needed to be able to run the holesky test in #150
> ci: give holesky-test workflow access to secrets via pull_request_target

- Makefile
- e2e/setup.go
- verify/cli.go
Made a mistake in https://github.com/Layr-Labs/eigenda-proxy/pull/146
paths should have remained the same given that they are relative to where the binary is run from, not where the go file lives. Fixed and added a comment to that effect.
> fix: verifier srs flags paths

- README.md
- e2e/setup.go
- server/config_test.go
- store/precomputed_key/s3/cli.go
- store/precomputed_key/s3/s3.go
Adding a new `--s3.enable-tls` command line flag to optionally enable SSL connection with the S3 endpoint.
Default value for the new flag is `false` to keep current behaviour. 
I have tested with GCP GCS (`--s3.endpoint=storage.googleapis.com`), that requires a secure connection.
> Added --s3.enable-tls flag

- cmd/server/entrypoint.go
- flags/eigendaflags/cli.go
- flags/eigendaflags/deprecated.go
- flags/flags.go
- store/generated_key/memstore/cli.go
- verify/cli.go
- verify/deprecated_flags.go
Recent flags refactor PR changed a bunch of flags. Added some those deprecated flags back, crashing the program if they are ever used to force users to change to the new flags.
I'm sure I missed a bunch of flags though given that the flags have been dispersed locally in a bunch of different modules. Would be a tough job to make sure to get all the deprecated flags... I propose we leave it at this. @bxue-l2 wdyt?
> chore: add deprecated flags to force early crash when used

- store/precomputed_key/s3/s3.go
Fixes #
The PR fixes the upload process on Google Storage (using its S3 compatibility API). Right now (with `main` config) the objects uploaded to Google Storage can have multiple `<size>;chunk-signature=<bytes>` strings in the file, which breaks the verification of the file on the get() stage.
Adding `DisableContentSha256 = true` to `putObjectOptions` used by minio client, the upload seems to be done properly and the chunk-signatures not included.
More info [here](https://github.com/minio/minio-go/issues/1922).
> Disable chunk encoding for `put` requests to Google Cloud Storage

- .github/workflows/build.yml
- .github/workflows/holesky-test.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
- Dockerfile
We updated go.mod to use go1.22 recently, but forgot to update the ci workflows.
Here's an example of a broken workflow: https://github.com/Layr-Labs/eigenda-proxy/actions/runs/11304509810/job/31449520854
Fixes #
> fix(ci): update go1.21->1.22 everywhere

- verify/verifier.go
Think this is a bug... but not 100% sure. So please verify that this is correct.
Fixes #
> fix: fetch quorum parameters from edasm at RBN instead of latest block

- .github/workflows/lint.yml
- flags/eigendaflags/cli.go
- go.mod
- go.sum
- server/config.go
- store/generated_key/eigenda/eigenda.go
- store/generated_key/memstore/memstore.go
- store/manager.go
- store/precomputed_key/redis/redis.go
- store/precomputed_key/s3/s3.go
- store/secondary.go
- store/store.go
- utils/utils.go
- verify/cert.go
- verify/cli.go
- verify/deprecated_flags.go
- verify/verifier.go
This PR depends on https://github.com/Layr-Labs/eigenda/pull/821 being merged first.
Main simplification that this allows is getting rid of the very complex retry logic that we had where an inner functionw as returning an error that was being caught by a very outward for loop, which was hard to understand. This PR makes that logic more local, but I opted to still keep the check in eigenda-proxy as well as an assert/safety guarantee. Think we also need it in the Get route... but not super familiar with that code path cc @epociask to make sure logic in this PR still works for that.
Fixes #
> refactor: use batch confirmation that was upstreamed to eigenda client

- .github/workflows/holesky-test.yml
- .vscode/settings.json
- e2e/main_test.go
- e2e/setup.go
- go.mod
- go.sum
- server/handlers.go
- server/middleware.go
was missing ethrpc and svcmanageraddr
Also realized `pull_request_target` was super wrong...... reverted that commit.
pull_request_target by default checks out the target branch! so all the tests were being done against main branch and not the PR branch..
Fixes #
> fix(e2e tests): missing new eigenda-client required config fields

- README.md
- common/common.go
- common/common_test.go
- common/store.go
- e2e/main_test.go
- e2e/safety_checks_test.go
- e2e/server_test.go
- e2e/setup.go
- flags/eigendaflags/deprecated.go
- flags/flags.go
- server/config.go
- server/config_test.go
- server/handlers.go
- server/load_store.go
- store/cli.go
- store/deprecated_flags.go
- store/generated_key/eigenda/eigenda.go
- store/generated_key/memstore/memstore.go
- store/manager.go
- store/precomputed_key/redis/redis.go
- store/precomputed_key/s3/s3.go
- store/secondary.go
- store/store.go
- store/store_test.go
- verify/cli.go
Fixes #191
- Removed `routing` flag category in favor of `storage`
- Created deprecated flag category for `routing` 
- Introduce store config struct with CLI flags and cfg invariants declared in `/store` package
> fix(#191): Routing namespace --> Storage

- Makefile
- cmd/server/entrypoint.go
- e2e/setup.go
- store/precomputed_key/redis/redis.go
- store/precomputed_key/s3/s3.go
- verify/verifier.go
> fix: Hide other sensitive cfg values

- client/simple.go
> chore(simple_client): Add explicit ServiceUnavailable error type

- client/simple.go
- flags/eigendaflags/cli.go
- server/config.go
- server/config_test.go
Fixes a config processing bug where cert verification can be disabled but the application will crash since the service manager and eth rpc params are still required even-though they shouldn't be. 
Created https://github.com/Layr-Labs/eigenda-proxy/issues/206 to identify that there are better solutions.
> fix: Disable `SERVICE_MANAGER_ADDR` & `ETH_RPC` as mandatory

- client/simple.go
> chore: Add mockable http client to simple client

- README.md
- client/client.go
- commitments/mode.go
- e2e/main_test.go
- e2e/safety_checks_test.go
- e2e/server_test.go
- server/handlers.go
- server/handlers_test.go
- server/routing.go
- store/manager.go
> chore: SimpleClient -> Standard Client

- README.md
- client/client.go
- client/go.mod
- commitments/mode.go
- e2e/main_test.go
- e2e/safety_checks_test.go
- e2e/server_test.go
- go.mod
- server/handlers.go
- server/handlers_test.go
- server/routing.go
- store/manager.go
This will make it easier to import it into other projects without importing all of the other dependencies of our root go.mod
TODO steps:
1. merge this PR with a replace directive in the main go.mod
2. release v0.1.0 of the new client module
3. make a new PR to use that version in the main go.mod file
4. release v1.6.1 of main module that uses the new client module
Fixes #
> feat: separate simple client into its own module

- Dockerfile
- Dockerfile.dockerignore
When building the Dockerfile at the project's root, it fails because a `go.mod` file is missing.
Copy the missing `go.mod` file (`client/go.mod`) along with the root's `go.mod`. This requires adding the file to the `Dockerfile.dockerignore` as an exception.
> fix: copy `client/go.mod` to `builder` in Dockerfile

- verify/merkle.go
- verify/merkle_test.go
- Remove the incorrect invariant check, which would fail proof with 0 length
- Add unit test to confirm 0 length proofs can succeed verification
- closes https://github.com/Layr-Labs/eigenda-proxy/issues/215
> Fix single node tree verification bug

- store/generated_key/memstore/memstore.go
This PR addresses a bug in memstore Put route.
The data_length should have returned number of symbols as opposed to number of bytes.
> fix: memstore returns data_length in number of symbols instead of bytes

- Makefile
- README.md
- These doc updates are being made in advance of the next proxy release
> docs: fix readme test docs, and add test comments to makefile

- server/handlers.go
> fix(sigmap-EDAP-04): Add IO parsing size constraint on incoming request bodies

- store/generated_key/eigenda/eigenda.go
- verify/certificate.go
> fix(sigmap-EDAP-01): Missing nil Checks On Parameters Of Incoming Requests

- verify/verifier.go
As pointed out by auditors, initial curve check was first mapping the commitment's X,Y field elements to the curve's G1 group before doing the inclusion check which would always resolve true even if invalid points are provided. 
Fixes #
> fix: Field element casting to affine representation

- verify/cert.go
Fixes #258 
Forgot to remove this call in https://github.com/Layr-Labs/eigenda-proxy/pull/241
Fixes #
> fix: remove last eth_call that required archive node

- docker-compose.yaml
- scripts/create-test-s3-bucket.sh
- server/load_store.go
- store/generated_key/memstore/memstore.go
- store/manager.go
- store/secondary.go
> chore: Update compose with secondary store setup && minor refactors

- .golangci.yml
- Makefile
- cmd/server/entrypoint.go
- e2e/setup.go
- server/config.go
- server/config_test.go
- server/handlers_test.go
- server/load_store.go
- server/routing.go
- server/routing_test.go
- server/server.go
- store/generated_key/memstore/README.md
- store/generated_key/memstore/cli.go
- store/generated_key/memstore/memconfig/config.go
- store/generated_key/memstore/memconfig/http_handlers.go
- store/generated_key/memstore/memconfig/http_handlers_test.go
- store/generated_key/memstore/memstore.go
- store/generated_key/memstore/memstore_test.go
- verify/cert.go
- verify/verifier.go
This is needed to create API-driven tests on the kurtosis devnet in our [op fork](https://github.com/Layr-Labs/optimism).
See the new memstore README for details of the REST API.
Fixes #
> feat: add http routes and handlers to get/patch the memstore config

- store/generated_key/memstore/memstore.go
Fixes #
Compute batch header hash. Needed for securely testing arbitrum integration: https://github.com/Layr-Labs/nitro/pull/71
> chore(memstore): Compute batch header hash before persisting

- common/common.go
- config/config_test.go
- config/eigendaflags/v2/cli.go
- go.mod
- go.sum
- store/builder.go
- This PR reworks how v2 initialization is done
- it moves builder logic into helper methods, and uses basic constructors instead of the builders defined in the core repo. IMO it makes sense for proxy to define these builders, and the base classes should just have constructors which accept complete subcomponents
- closes https://github.com/Layr-Labs/eigenda-proxy/issues/272 (e2e tests now pass with client side proving enabled)
> Rework v2 initialization

- e2e/safety_checks_test.go
e2e tests were turned off by mistake for a while. https://github.com/Layr-Labs/eigenda-proxy/pull/299 just turned them back on. Not sure why the test was only caught by CI after merging. But this commit fixes the failing test.
Fixes #
> test: fix failing e2e-local safety check

- store/generated_key/eigenda/eigenda.go
- verify/v1/certificate.go
Fixes #
Mitigates risk where the disperser can increase the size of dynamic array fields to be larger than their expected size limit with verification still passing. If performed, the disperser could:
1. Overload DA commitment sizes used for batcher inbox submissions on OP x EigenDA rollups to grief
2. Break secondary storage on Arbitrum x EigenDA rollups by providing a cert that can't be regenerated perfectly when doing get queries when deriving L2 state from the sequencer inbox 
Having this size enforcement also securely enables https://github.com/Layr-Labs/nitro/pull/76
> fix: Enforce V1 cert field sizes

- Makefile
- fuzz/server_fuzz_test.go
- testutils/setup.go
Cleaned up the fuzz tests to actually do something Reduced seed corpus to 3 meaningful inputs
Removed cluttering log outputs so we can actually see the fuzzer output as its finding new interesting cases
Here's an output of running `make test-fuzz`:
Fixes #
> test(fuzz): fix fuzz tests

- .github/workflows/per-pr.yml
- Dockerfile
- Makefile
Used to be "eigenda-proxy". Renamed for consistency with `docker-build` command. Also most people are used to just typing `make build`, which doesn't require knowing the binary name.
Fixes #
> chore(make): rename build command

- .env.exampleV1AndV2.holesky
- README.md
- common/common.go
- config/flags.go
- config/proxy_config.go
- config/server_config.go
- docs/help_out.txt
- server/handlers.go
- server/handlers_test.go
- server/routing.go
- server/server.go
- closes DAINT-420
-  [link](https://linear.app/eigenlabs/issue/DAINT-420/create-admin-http-endpoints-to-get-and-set-dispersetov2)
- closes DAINT-389
- [link](https://linear.app/eigenlabs/issue/DAINT-389/docs-document-v2-migration)
- adds new flag 
```
&cli.BoolFlag{
Name:     AdminEndpointsEnabledFlagName,
Usage:    "Enable administrative HTTP endpoints for runtime configuration",
Value:    false,
EnvVars:  common.PrefixEnvVar(envPrefix, "ADMIN_ENDPOINTS_ENABLED"),
Category: category,
},
```
> Implement admin endpoints for v2 dispersal

- go.mod
- go.sum
- Use pending core release 0.9.0
> chore: bump eigenda to v0.9.0

- testutils/setup.go
- Increases timeouts, since e2e tests against testnet are failing otherwise
> feat: Increase test timeouts so e2e tests pass against testnet

- .env.exampleV1AndV2.holesky
- .env.exampleV2.holesky
- docs/help_out.txt
- store/storage_manager_builder.go
- testutils/setup.go
- verify/cli.go
- Remove user facing "load g2 points" option, since it can be explicitly set correctly for each case, without user input
- Deletes `ReadG2PointsFlag`. This isn't a breaking change, since a version of proxy has never been released with it.
```
&cli.BoolFlag{
Name:     ReadG2PointsFlagName,
Usage:    "Whether to read in G2 SRS points.",
EnvVars:  []string{withEnvPrefix(envPrefix, "READ_G2_POINTS")},
Value:    false,
Category: category,
},
```
> feat: Remove user facing load g2 option

- common/client_config_v1.go
- common/client_config_v2.go
- config/eigendaflags/cli.go
- config/proxy_config_test.go
- config/v2/eigendaflags/cli.go
- docs/help_out.txt
- store/generated_key/eigenda/eigenda.go
- store/generated_key/utils/store_utils.go
- store/generated_key/v2/eigenda.go
- store/storage_manager_builder.go
- testutils/setup.go
- closes DAINT-419
- [link](https://linear.app/eigenlabs/issue/DAINT-419/make-putretries-configuration-more-user-friendly) 
- `PUT_RETRIES` for both v1 and v2 flags is now an `int` instead of a `uint`, to support more intuitive configuration (old logic interprets 0 to mean retry forever)
```
&cli.IntFlag{
Name: PutRetriesFlagName,
Usage: "Total number of times to try blob dispersals before serving an error response." +
">0 = try dispersal that many times. <0 = retry indefinitely. 0 is not permitted (causes startup error).",
Value:    3,
EnvVars:  []string{withEnvPrefix(envPrefix, "PUT_RETRIES")},
Category: category,
},
```
- This is *technically* a breaking change, in case anyone was relying on the old behavior where config value `0` yields infinite retries. Practically, my guess would be …
> chore!: Clean up put retries

- .env.exampleV1AndV2.holesky
- .env.exampleV2.holesky
- .golangci.yml
- common/client_config_v2.go
- common/eigenda_network.go
- config/proxy_config.go
- config/proxy_config_test.go
- config/v2/eigendaflags/cli.go
- docs/help_out.txt
- e2e/server_test.go
- go.mod
- go.sum
- store/generated_key/memstore/memstore_test.go
- store/generated_key/v2/eigenda.go
- store/storage_manager_builder.go
- testutils/setup.go
- verify/verifier.go
- verify/verify_test.go
- closes DAINT-322
- [link](https://linear.app/eigenlabs/issue/DAINT-322/v2-optional-distributed-retrieval-w-eigenda-operator-set) 
- closes EGDA-1094
- [link](https://linear.app/eigenlabs/issue/EGDA-1094/add-optional-network-id-flag-to-populate-other-config-fields)  
DO NOT MERGE:
- Given that we have recently released V2 proxy support, it's likely we will need to release patches in the near future
- This PR update the eigenda core dependency to the latest `master` commit, since doing so is required to implement blob retrieval from validator nodes.
- proxy releases should only be made with a dependency on an official core release. Until a new core release is cut which includes the necessary changes to support distributed retrieval, this PR will need to remain as a feature branch
The …
> feat: Implement validator node blob retrieval

- Makefile
- go.mod
- go.sum
- store/generated_key/memstore/v2/memstore.go
- store/storage_manager_builder.go
- verify/cert.go
- verify/hasher.go
- verify/hasher_test.go
- Updates to the most recent core commit, to be able to make a proxy release candidate
- I wasn't able to point to the exact `v0.9.0-rc.3` core tag, since that commit is missing the v1 bindings, which weren't added back in until core commit `dbc01a215a2811a8d4c30178b892dbd44694fc5b`, which is what I had to use
> feat: Use most recent core commit

- store/generated_key/memstore/v2/memstore.go
This PR changes the rbn when used with v2 memstore
The motivation comes from a need to test OP secure integration. The hokulea is implementing the recency [check](https://github.com/Layr-Labs/hokulea/pull/121). All tests in hokulea are done with a kurtosis devnet where eigenda-proxy is configured in memstore mode.
V2 memstore currently chooses a random number from 0 to 32 for a rbn. It essentially fails all DA certs due to the recency check.
The change adds a large number to rbn while preserving the randomness. Because rbn is so large, the recency check will never fail, https://github.com/Layr-Labs/eigenda/blob/master/docs/spec/src/integration/spec/6-secure-integration.md#1-rbn-recency-validation.
Having this change allows regular and CI test on hokulea
> improve: increase rbn for memstore v2

- .vscode/settings.json
- test/e2e/server_test.go
- test/testutils/setup.go
- Enable V1 cert verification in e2e tests
- Remove duplicate server test
- `testProxyClient` and `testProxyClientWriteRead` were functionally the same
- Reorganize server tests
- put "basic test" at the top
- put utility functions at the bottom
- Make some tweaks to `settings.json`
- I don't think it's a good idea to have a private key field in a committed file: you're just asking to leak the key like that. New `settings.json` relies on a `.env` to hold required vars for tests
- I added a 5m test timeout, to override the default 30s
> chore: Clean up tests

- docs/help_out.txt
- store/generated_key/eigenda/verify/cert.go
- store/generated_key/eigenda/verify/cli.go
- store/generated_key/eigenda/verify/verifier.go
- Adds support for cert verification with custom quorums and thresholds by allowing an optional `EigenDACertVerfiierV1` address to be provided for which the required quorums and thresholds are read from 
Fixes #
> feat: Optional EigenDACertVerifierV1 support for reading quorums/thresholds

- common/client_config_v2.go
- common/eigenda_network.go
- store/builder/storage_manager_builder.go
The behavior of proxy sould work fine for any external customers. But the way the chainid check is currently implemented makes it impossible to start proxy on our preprod environment. This PR fixes that.
> It had testnet hardcoded on chainid 17000, so wasn't possible to start proxy on preprod (which is also on 17000).
> Changed to alow multiple eigneda networks per chainid
Fixes #
> fix: network id check bug (can't start on preprod)
