Layr-Labs/eigenda-proxy

pull_request_template.md
Taken from [pessimism](https://github.com/base-org/pessimism/blob/master/pull_request_template.md)
=> chore: PR template

.github/workflows/actions.yml, Makefile, e2e/main_test.go, e2e/optimism_test.go, e2e/server_test.go, e2e/setup.go
N/A
- remove Optimism flag
- Run holesky test against OP stack
=> chore: Cleanup E2E tests

.github/release-drafter.yml, .github/workflows/release-drafter.yml
https://github.com/release-drafter/release-drafter
Hopefully should cut the time it takes to write release notes.
=> Enable release-drafter

.github/workflows/gchr.yml
Fixes #https://github.com/Layr-Labs/eigenda-proxy/issues/2
=> feat: GHCR push support

Dockerfile
=> chore: Add SRS points to dockerfile

Dockerfile
=> chore: Update dockerfile to use srs points

Dockerfile
=> chore: Update dockerfile

README.md
=> Update README.md docker

README.md
As title, remove ext data type from ReadMe, as it is currently not specified in OP nor is added in the code
=> remove ext data type

e2e/server_test.go
=> fix: Oversized blob test

README.md, server/config.go
=> chore: Update G1 default value

README.md, cmd/server/entrypoint.go, server/config.go, store/eigenda.go
=> chore: lagniappe v1.4 updates

pull_request_template.md
=> chore: less verbose PR template

e2e/server_test.go, e2e/setup.go, go.mod, go.sum, verify/verifier.go
=> chore: Update eigenda dep to v0.8.1 && update tests for 16MB blobs

store/memory.go
Just a small change for readability.
=> chore: rename memstore eventLoop -> pruningLoop

go.mod, go.sum
Need access to https://github.com/Layr-Labs/eigenda/pull/764
Fixes #
=> dep: update eigenda to latest version for latest eigenda-client logging behavior

server/server.go
=> chore: remove unused tls logic

server/load_store.go, server/server.go, store/eigenda.go
Just a small PR to help filter out eigenda-client log lines by adding to their logger a subsystem label.
Added 2 more small cleanups in this PR.
=> Eigenda client subsystem logger

go.mod, go.sum
Getting ready for our new release. 
Fixes #
=> feat: update eigenda latest release v0.8.4

cmd/server/entrypoint.go, flags/flags.go, verify/cli.go
Another bug from my #146 ... :\
=> fix: import and expose the verifier flags

.env.example.holesky, .env.example.mainnet, README.md
Update Readme and template .env based on the latest flag introduced in #165
=> update readme and template

cmd/server/entrypoint.go
=> hide eth rpc, format hidden string

flags/eigendaflags/cli.go
=> docs: better usage docs for signer-private-key flag

verify/cli.go
=> fix(sigmap-EDAP-04): Miscellaneous General Comments

README.md
=> docs: update readme shields to point to actual workflows

verify/cert.go
=> fix(#251): better error logging for RPC lookup errors against service manager

SECURITY.md
=> docs: update SECURITY.md with audit commit + fix small typos

common/store.go, metrics/metrics.go, store/generated_key/eigenda/eigenda.go, store/secondary.go
=> chore: fix miscellaneous typos in comments

.github/workflows/codeql-scanning.yml
Including Go Queries from Trail of Bits for CodeQL.
=> ci: add trailofbits/go-queries to codeql-scanning.yml

common/common.go, config/config.go, config/config_test.go, config/eigendaflags/v2/cli.go, e2e/setup.go, server/server.go, store/builder.go
- introduces user injection for custom quorums
- adds additional config checks and tests to enforce V2 config expressions 
- sets `MaxGRPCMessageSize` for reading from relays to `MaxBlobSizeBytes + 10% buffer`
- Introduces `BlockNumberPollIntervalFlagName` flag
- Update flag descriptions
=> chore(V2): update config checks and fix custom quorum injection

store/generated_key/memstore/memstore.go
=> chore(memstore): hash entire cert + remove cert verification

.golangci.yml, cmd/server/entrypoint.go, common/common.go, config/config.go, config/config_test.go, config/eigendaflags/v2/cli.go, e2e/setup.go, go.mod, go.sum, store/builder.go, store/generated_key/memstore/ephemeraldb/ephemeral_db.go, store/generated_key/memstore/ephemeraldb/ephemeral_db_test.go, store/generated_key/memstore/memstore.go, store/generated_key/memstore/v2/memstore.go, store/generated_key/v2/eigenda.go, store/manager.go
- This PR updates to the most recent commit of EigenDA master, so that we can make necessary changes related to recent API modifications
- This PR fixes various linter errors
- This PR removes `forbigo` from the list of linters, as it was trying to forbid print statements entirely
=> Update EigenDA version, and fix linter issues

e2e/safety_checks_test.go
=> V2: fix e2e tests

README.md
Fixes #
- It fixes the cast command to create wallet `-j` is not a short for `--json`. so explicitly specifying `--json` since we expect it to be `json` in subsequent commands
=> chore: fix readme with correct cast cmd

README.md
=> docs: add readme link to v2 integration spec

.github/workflows/per-pr.yml, Makefile, docs/help_out.txt
Fixes https://github.com/Layr-Labs/eigenda-proxy/issues/345 
tested by updating the output file to reset the confirmation depth to 0 and made sure the CI job failed:
=> fix: Standard output check

README.md
=> docs(readme): add repo+release info

Makefile, e2e/safety_checks_test.go, e2e/server_test.go, go.mod, go.sum, store/manager.go
- closes DAINT-397 https://linear.app/eigenlabs/issue/DAINT-397/fix-non-local-e2e-tests
- updates to the most recent core DA commit
=> Fix e2e tests

server/handlers.go, server/routing.go
=> chore: Log capture potential 303 GET redirects on /put/

.envrc
This allows overwriting values in .env.exampleV1AndV2.holesky, for example for secret values
Fixes #
=> core(.envrc): load .env if it exists

store/storage_manager_builder.go
- closes DAINT-471
- [link](https://linear.app/eigenlabs/issue/DAINT-471/proxy-should-get-relay-registry-address-from-service-manager)
=> feat: Use reader as source for relay registry address

.env.exampleV1.sepolia, .env.exampleV1AndV2.sepolia, .env.exampleV2.sepolia, .github/workflows/per-pr.yml, Makefile, common/eigenda_network.go, config/v2/eigendaflags/cli.go, docs/help_out.txt, testutils/setup.go
Fixes https://github.com/Layr-Labs/eigenda-proxy/issues/394
- Added Sepolia network constants and addresses for
EigenDA contracts
- Created environment configuration files for
Sepolia deployments
- Updated CI workflow for testing with Sepolia
network
- Minor code improvements for network handling
=> feat: Sepolia Network Support

go.mod, go.sum, store/builder/storage_manager_builder.go, store/generated_key/v2/eigenda.go
=> chore: Update eigenda v2 store to use latest legacy verification

store/generated_key/eigenda/verify/verifier.go
=> fix: Take in verifyCerts boolean in Verifier constructor
